services:
  database:
    secrets:
    - psql_passwd
    build:
      context: ./database
      dockerfile: dockerfile
    expose:
      - 5432
    networks:
      - server-side
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/psql_passwd
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_backup:/var/lib/postgresql/backup
    
  flask_server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
    - 5000:5000
    networks:
      - server-side
      - client-side
    environment:
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/1
      - DB_HOST=192.168.0.21
      - DB_PASS=2137
      - DB_PORT=5432
      - DB_SCHEMA=anime_suggester
      - DB_USER=anime_suggester_client
      - MAL_CLIENT_ID=48563b906310d3fdb4cefa1c1877bfc3
      - MAL_CLIENT_SECRET=7d1c1c9dff161b5bf61dbbb1cc8ceed03d7988db888fc702ef8b9a6ebff7de7e
    depends_on:
      - database
      - redis-backend

  redis-backend:
    image: redis:latest
    expose:
      - 6379:6379
    networks:
      - server-side

  proxy:
    image: nginx:latest
    volumes:
      - ./build_files/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - client-side
    depends_on:
      - flask_server

networks:
  server-side:
  client-side:

volumes:
  db_data: {}
  db_backup: {}

secrets:
    psql_passwd:
        file: ./build_files/secrets/psql_passwd