services:
  database:
    secrets:
    - psql_passwd
    build:
      context: ./database
      dockerfile: dockerfile
    expose:
      - 5432:5432
    networks:
      - server-side
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/psql_passwd
    volumes:
      - db_data:/var/lib/postgresql/data
    
  flask_server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
    - 5000:5000
    - 5555:5555
    networks:
      - server-side
      - client-side
    environment:
      - CELERY_BROKER_URL=redis://redis_backend:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_backend:6379/1
      - DB_HOST=database
      - DB_PASS=2137
      - DB_PORT=5432
      - DB_SCHEMA=anime_suggester
      - DB_USER=anime_suggester_client
      - MAL_CLIENT_ID=48563b906310d3fdb4cefa1c1877bfc3
      - MAL_CLIENT_SECRET=7d1c1c9dff161b5bf61dbbb1cc8ceed03d7988db888fc702ef8b9a6ebff7de7e
      - TEMPLATE_PATH=/home/anime_suggester/templates/
      - STATIC_PATH=/home/anime_suggester/static/
    depends_on:
      - database
      - redis_backend

  redis_backend:
    image: redis:latest
    restart: always
    command: redis-server --save 60 1
    expose:
      - 6379:6379
    networks:
      - server-side

  proxy:
    image: nginx:latest
    volumes:
      - ./build_files/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - client-side
    depends_on:
      - flask_server

networks:
  server-side: {}
  client-side: {}

volumes:
  db_data: {}

secrets:
    psql_passwd:
        file: ./build_files/secrets/psql_passwd
