services:
  database:
    secrets:
    - psql_passwd
    build:
      context: ./database
      dockerfile: dockerfile
    expose:
      - 5432:5432
    networks:
      - server-side
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_passwd
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_backup:/var/lib/postgresql/backup
    
  flask_server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
    - 5000:5000
    - 8000:8000
    - 5555:5555
    networks:
      - server-side
      - client-side
    secrets:
      - jwt_public_key
      - jwt_private_key
    environment:
      - CELERY_BROKER_URL=redis://redis_backend:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_backend:6379/1
      - DB_HOST=database
      - DB_PASS=2137
      - DB_PORT=5432
      - DB_SCHEMA=anime_suggester
      - DB_USER=anime_suggester_client
      - MAL_CLIENT_ID=${MAL_CLIENT_ID}
      - MAL_CLIENT_SECRET=${MAL_CLIENT_SECRET}
      - TEMPLATE_PATH=/home/anime_suggester/templates/
      - STATIC_PATH=/home/anime_suggester/static/
      - JWT_PUBLIC_KEY_FILE=/run/secrets/jwt_public_key
      - JWT_PRIVATE_KEY_FILE=/run/secrets/jwt_private_key
    depends_on:
      - database
      - redis_backend

  redis_backend:
    image: redis:latest
    restart: always
    command: redis-server --save 60 1
    expose:
      - 6379:6379
    networks:
      - server-side

  proxy:
    image: nginx:latest
    volumes:
      - ./build_files/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - client-side
    depends_on:
      - flask_server

networks:
  server-side: {}
  client-side: {}

volumes:
  db_data: {}
  db_backup: {}

secrets:
    psql_passwd:
        file: ./build_files/secrets/psql_passwd
    jwt_public_key:
        file: ./build_files/secrets/jwtRS256.key.pub
    jwt_private_key:
        file: ./build_files/secrets/jwtRS256.key
