#!/bin/bash

NAME=flower
DESC="flower daemon"

# Name of the projects settings module.
export DJANGO_SETTINGS_MODULE="yourproject.settings"

# Path to virtualenv
ENV_PYTHON="python"

# Where the Django project is.
FLOWER_CHDIR="/home/anime_suggester/"

# How to call "manage.py celery flower" (args...)
FLOWERCTL="flower -A runner.celery --port=5555"
DAEMON=$FLOWERCTL

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "

        start-stop-daemon --start --pidfile /var/tmp/$NAME.pid \
            --chdir $FLOWER_CHDIR --chuid celery \
            --user celery --group celery --background \
            --make-pidfile \
            --exec "$ENV_PYTHON" -- $FLOWERCTL
        echo "$NAME."
        ;;

  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --quiet --oknodo \
            --pidfile /var/tmp/$NAME.pid
        rm -f /var/tmp/$NAME.pid
        echo "$NAME."
        ;;
esac

exit 0

