FROM postgres:15.2-bullseye as base

EXPOSE 5432

RUN mkdir "/home/anime_suggester" && chown postgres:postgres "/home/anime_suggester"
WORKDIR /home/anime_suggester

ADD ./database_dump.sql /docker-entrypoint-initdb.d/
ADD ./auto_backup.sh /home/anime_suggester/

# Add crontask for creating backup
#RUN crontab -l 2>/dev/null; echo '0 7 * * * /home/anime_suggester/auto_backup.sh' | crontab -